name: Code Coverage Report

on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  jest-coverage-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test -- --coverage
          working-directory: ./client

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
          working-directory: ./client

      - run: npm run report:coverage:summary
        working-directory: ./client