name: Code Coverage Report

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  jest-coverage-report:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4

      - name: 🛠 Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 📦 Install Project Dependencies
        run: npm install
        working-directory: ./client

      - name: 🚀 Run Jest with coverage
        run: npm run jest:run -- --coverage
        working-directory: ./client

      - name: Create Jest Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./client/jest-coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          output: both

      - name: Add Jest Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: Jest Unit Tests Code Coverage Summary
          recreate: true
          path: code-coverage-results.md
          message:
            ${{ github.event.pull_request.title }}, Release ${{ github.sha }} to <https://deploy-preview-${{ github.event.number }}--memorymania.netlify.app/>

  cypress-coverage-report:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4

      - name: 🌲 Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
          working-directory: ./client

      - run: npm run report:coverage:summary
        working-directory: ./client

      - name: Create Cypress Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./client/cypress-coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          output: both

      - name: Add Cypress Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: Cypress Tests Code Coverage Summary
          recreate: true
          path: code-coverage-results.md
          message:
            ${{ github.event.pull_request.title }}, Release ${{ github.sha }} to <https://deploy-preview-${{ github.event.number }}--memorymania.netlify.app/>