name: Jest Coverage Report

on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  jest-coverage-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      #      - name: Upload Jest coverage report
      #        uses: ArtiomTr/jest-coverage-report-action@v2
      #        with:
      #          github-token: ${{ secrets.GITHUB_TOKEN }}
      #          test-script: npm run test -- --coverage
      #          working-directory: ./client

      #      - name: Generate Cypress coverage report
      #        run: npx cypress open
      #        working-directory: ./client

      - name: Comment Cypress coverage report on PR
        uses: cypress-io/github-action@v6
        with:
          start: |
            npm run build
            npm run dev &
            npx cypress run --headless --browser chrome
            npx nyc report --reporter=text-summary
          working-directory: ./client
